span: {start: "2018-01-01", end: "2022-12-31"}
cadence_minutes: 12
window_hours: 48
window_stride_hours: 6
targets_hours: [6, 12, 24]
censoring: {cmd_deg_threshold: 70}
resize: {target_px: 256}
paths:
  raw_dir:       "data/test/raw"
  interim_dir:   "data/test/interim"
  processed_dir: "data/test/processed"
  cache_dir:     "data/test/cache"
  logs_dir:      "data/test/logs"
