# configs/train_pinn_real.yaml
# Training config for REAL SHARP data

seed: 42
device: "cpu"  # Change to "cuda" if GPU available

model:
  hidden: 384
  layers: 10
  learn_eta: false
  eta_scalar: 0.01
  fourier:
    max_log2_freq: 5
    ramp_frac: 0.6

classifier:
  hidden: 256
  dropout: 0.1
  horizons: [6,12,24]

physics:
  enable: false         # P0: data-only (set true for P1+)
  resistive: false
  boundary_terms: false
  lambda_phys_schedule:
    - [0.00, 0.0]
    - [0.30, 0.0]
    - [0.80, 3.0]
    - [1.00, 5.0]

eta:
  min: 1.0e-4
  max: 1.0
  tv_weight: 1.0e-3

loss_weights:
  cls: 1.0
  data: 1.0

collocation:
  n_max: 50000
  alpha_start: 0.5
  alpha_end: 0.8
  impw_clip_quantile: 0.99

train:
  steps: 1000     # Start small, increase to 10k+ for real training
  batch_size: 1
  lr: 1.0e-3
  grad_clip: 1.0
  amp: false
  log_every: 50

data:
  use_real: true  # USE REAL SHARP DATA
  windows_parquet: "data/interim/windows_train.parquet"
  npz_root: "S:/flare_forecasting"
  frames_meta_parquet: "S:/flare_forecasting/frames_meta.parquet"
  target_size: 256

